### ISSUE TITLE
GET error (500 internal server error)

### ISSUE THREAD

**Issue by jbavington** [bakerframework/bakercloud-ce-console#37] opened 2014-05-08 14:27 UTC
Hi there,

When testing my app on a device and trying to purchase an issue, I receive the following error in the Xcode log:

2014-05-08 09:58:01.040 About Canada[650:6523] [ERROR] Failed GET request to http://aboutcanadanewsinfo.ca/api/purchases/ca.rb.aboutcanada/BC5E9B78-BDCD-4BCC-9849-DAFAE51C37FB?environment=debug: response was 500 internal server error

On perhaps a similar note, this test URL works fine and shows results:
http://aboutcanadanewsinfo.ca/api/purchases/com.nin9creative.baker/D5DBF605-995F-4D66-8393-45D1017D12B9

However, when using my actual App ID and device I get a "website error" message:
http://aboutcanadanewsinfo.ca/api/purchases/ca.rb.aboutcanada/BC5E9B78-BDCD-4BCC-9849-DAFAE51C37FB

I've checked the .htaccess file and believe it's set up correctly.  If I change the RewriteBase, it returns a 404 to the above URL's instead.

Purchases backend screenshot (I had to manually put in the Product ID as it was leaving it blank):
![screen shot 2014-05-08 at 10 26 00 am](https://cloud.githubusercontent.com/assets/4700969/2916581/ea9b8d3c-d6bc-11e3-8c38-1bd98b8e54ff.png)

Receipts screenshot (Product ID and Purchase Date are always blank...):
![screen shot 2014-05-08 at 10 26 33 am](https://cloud.githubusercontent.com/assets/4700969/2916586/ed9b2830-d6bc-11e3-99a7-45e1dfb26b90.png)

Can you please let me know what I have missed?  

Thanks in advance.

Jason

**Comment by nin9creative** [comment] 2014-05-08 21:51
Have you confirmed that CURL is enabled on your server?  I've seen that sometimes the receipt checking with apple will
fail because of this and result in a failure/blank product id.

Andrew

**Comment by jbavington** [comment] 2014-05-09 13:19
Hey Andrew,

Yes, CURL is enabled.  Here's the phpinfo screenshot for that section, thanks.

![screen shot 2014-05-09 at 9 19 14 am](https://cloud.githubusercontent.com/assets/4700969/2928405/94a44138-d77c-11e3-9b8d-5b2b61d60c48.png)

Jason

**Comment by jbavington** [comment] 2014-05-12 13:14
Hi Andrew,

Any thoughts as to what else I might be able to try to coax the system into logging receipts and the product id?

Thanks.

Jason

**Comment by nin9creative** [comment] 2014-05-12 18:08
Not off the top of my head.  The only similar issue that I had seen was when CURL wasn't working.

Are you able to see any lower level PHP error logs or the like?

Andrew

**Comment by jbavington** [comment] 2014-05-13 18:02
I checked with the web host company and they say that their database server doesn't accept remote connections.  Might that be the issue?

Thanks.

Jason

**Comment by nin9creative** [comment] 2014-05-13 23:56
Did you ever have this working?  I seem to remember past discussions...

Are there any errors in the system log table?

Regards,
Andrew

**Comment by jbavington** [comment] 2014-06-06 18:28
Hi Andrew,

I worked on this yesterday to coax some more "500" errors.  Checked the error logs from yesterday and they're still blank.

I've unfortunately never gotten this to work on this server (after trying off and on since the beginning of the year).  Not sure what else to try.

Any thoughts?

Thanks.

Jason

**Comment by nin9creative** [comment] 2015-04-20 16:15
Closing due to age of issue.  Please reopen if still required.

**Closed as completed by nin9creative** 2015-04-20 16:15 UTC
