### ISSUE TITLE
Push notifications question

### ISSUE THREAD

**Issue by fobetor** [bakerframework/bakercloud-ce-console#4] opened 2013-12-04 16:45 UTC
Andrew
 Congrats!! I have just installed this vesion and it works fine. Perfect.... thanks for the program. Ah.. and the app has been approved... so I'm near release...
 Now.. two questions:
a) If I update the magazine content...Is Bakercloud able to send an update to the Baker app?
b) I dont find anywhere the explanaition about the iTunes Summary & iTunes Cover art fields... What are they for?

**Comment by nin9creative** [comment] 2013-12-04 16:50
a)  Unfortunately at this time, you'll have to implement Push Notifications for your app with something like Urban Airship or Parse.com
b)  The iTunes Summary and iTunes Cover Art fields are for the ATOM XML Feed for iTunes Connect.  You are able to set that up in iTunes Connect to point to your API for the ATOM Feed.

     Something like this:  http://apice.thebakercloud.com/itunes/com.nin9creative.baker
     It will produce the ATOM Feed that you can enter in the field on the Newsstand page in iTunes Connect

Andrew

**Comment by fobetor** [comment] 2013-12-04 17:00
Thank you.
...trying a urls such as 
http://api.mydomain.com/itunes/DY2TER4P3DF
Returns me a:
{"error":{"text":"Invalid APP ID"}}
Thats my app id in itunes conect....

**Comment by nin9creative** [comment] 2013-12-04 17:04
It needs to be the App ID (Bundle Identifier) that you are using in the MagRocket/Baker Cloud CE site.

**Comment by fobetor** [comment] 2013-12-04 17:07
Yes Andrew, thats my APP ID, in baker, baker cloud & Itunes Connect.... ;-)
For instance, if I try using the installed examples
http://api.mydomain.com/itunes/com.nin9creative.baker
I get a 404 error from the server...

**Comment by nin9creative** [comment] 2013-12-04 18:15
Does the issues call work?  If you are running with the CE version, the below APP ID should be 
in the sample data.

http://api.mydomain.com/issues/com.nin9creative.baker/123123123123

**Comment by fobetor** [comment] 2013-12-04 18:27
Andrew
 Yes, this call works fine. It returns
[{"name":"BakerMagazine-January","title":"January 2013","info":"Apple's Man of the Year Issue.","date":"2013-01-01 00:00:00","cover":"http:\/\/www.bakercontent.com\/publication\/com.nin9creative.baker\/BookCoverTemplate@2x.png","url":"http:\/\/api.XXXX.com\/issue... Bla bla bla (XXXX by me...)

**Comment by nin9creative** [comment] 2013-12-04 18:28
And you installed the CE version of the API?

Andrew

**Comment by fobetor** [comment] 2013-12-04 18:35
mmmmm...yes... I am going to confirm it now....mmmmmm

**Comment by fobetor** [comment] 2013-12-04 18:39
I think it is for the files that i see in the server...i cant find a file with the version in the header, but I deleted any previous files when installing it.

**Comment by nin9creative** [comment] 2013-12-12 04:33
Is this still a problem?  If not you can close the Issue.

**Closed as completed** 2013-12-12 07:08 UTC

**Comment by pppedant** [comment] 2014-01-10 08:47
Well I am experiencing exactly the same problem. I removed all the files and re-install fresh copy downloaded from git repo. But result is the same: {"error":{"text":"Invalid APP ID"}}

All other features are working without problem.

**Comment by pppedant** [comment] 2014-01-10 12:07
I guess the problem is originated from lines 419 & 420 of index.php as ITUNES_UPDATED column in ISSUES table seems NULL.

**Comment by nin9creative** [comment] 2014-01-10 14:14
Is this for the ATOM feed api call?<a href="http://overview.mail.yahoo.com?.src=iOS"><br/><br/>Sent from Yahoo Mail for iPhone</a>

**Comment by pppedant** [comment] 2014-01-10 14:21
yes for the atom feed.
