### ISSUE TITLE
how do i add a new field into user management ?

### ISSUE THREAD

**Issue by axilaris** [bakerframework/bakercloud-ce-console#19] opened 2014-02-07 16:14 UTC
If I enter BakerAdmin and go into User Manager, is there a way to add a new field ?

I want to add a new field called verified - enabled, disabled for the user.

I believe i edit/add crud_users.php, crud_users/crud_users.php, crud_users/user_verified.php.

but now i get an error like:
Message: unserialize() Error at offset 4134 of 6343 bytes
Filename: admin/user.php
Line number: 37

How do I serialize or set a new field ? what is the procedure to do it ?

**Comment by nin9creative** [comment] 2014-02-07 16:31
Really customization of user access is beyond the scope of the tool, the idea is to be able to manage publications
and internally for your publication have multiple users manage your magazines.

What specifically are you trying to accomplish?

Andrew

**Comment by axilaris** [comment] 2014-02-07 16:36
i dont understand why is this beyond the scope of the tool ? i just want to have the ability to verify my users, meaning, i want to disable them if i wanted to instead of deleting the user altogether.

why are you being secretive ? is this a proprietary software ?

**Comment by nin9creative** [comment] 2014-02-07 16:39
What are you talking about?  I was just asking a question regarding what the use case was.

I was just saying that the software was configured to manage publications, issues etc...  If you want to customize the user
portion, it's a bit more in depth.  I can provide details, but needed to know what you were trying to do.

**Comment by axilaris** [comment] 2014-02-07 16:47
ok fair enough, miscommunication.
like mentioned earlier, the use case is to turn on and off the user account without deleting it. some users i want to ban them for certain reasons you know like not paying customers, etc.

how do i accomplish adding an additional radio button field in the user manager ?

**Comment by nin9creative** [comment] 2014-02-07 16:57
So a larger question...  Are you trying to setup this as a multi user platform for multiple users managing different publications?

Because if that is the case you may run into many issues I believe.  It was intended as a backend install for a single publisher/developer (who may have multiple users that are required to have access to manage Baker publications).  If you are a developer providing a service for your clients, your best bet is to provide a separate install for each client you are deploying magazines for if you are wanting to give users access.  Right now there is no granularity for associating users with specific publications.  Users will be able to see all publications.

That being said - the user portion is slightly complicated in it's setup as the screens are rendered dynamically based on configuration.  Unfortunately editing that configuration isn't very
straightforward.  Modifying the Publication / Issue definitions are easy enough via the BakerAdmin login. That was the design intention, to allow an easy to modify platform for folks to 
configure without much coding necessary.  However the user setup itself isn't as easy to modify.   You can modify the database, obviously.

If you want to see how the underlying CRUD classes leverage the configuration, look at the FTP directory in your installation...

/application/config/database/(your db name)/

You'll see a crud_users folder and a crud_users.php

Play around with those files.

**Comment by axilaris** [comment] 2014-02-07 17:01
ok thanks for the insights.
my problem now is i cant serialize crud_users.php after adding the field. 

how do i validate crud_users.php ? what format is it ? because if i use json validator it still incorrect.

**Comment by nin9creative** [comment] 2014-02-07 17:42
If you want to be able to use the UI to configure that table, you can try the following.

First go to your Baker Cloud Console CE database.

Then go to the crud_permissionstable.

Add a new row.

group_id:  1
table_name:  crud_users

permission_type: 5

Then log in as the BakerAdmin

Put this in the URL.

http://www.yourdomain.com/index.php/admin/scrud/config?table=crud_users

This should bring up the configuration interface where you should be able to click the "+" sign to add the field that you already
added to the database to the UI.

**Comment by axilaris** [comment] 2014-02-07 18:06
I finally figured out. serialize and unserialize are PHP encoding. 
would appreciate if you could provide some real answers to the code.

anyway, sharing to all for those who wants to edit this console.
for example crud_users.php, copy the serialize data into this online unserializer
http://www.functions-online.com/unserialize.html

modify your data structure and paste it back to the online serializer
http://www.functions-online.com/serialize.html

thats basically it.

**Comment by nin9creative** [comment] 2014-02-07 18:14
Yes, sorry the php crud framework is using php encoding for the data structures and attributes...  

Again, the intention was to create a simple tool/interface for backend management with an API 
layer to get at the data for a Baker app.  I hadn't anticipated folks wanting to change the User
side of the equation.

Regards,
Andrew

**Comment by nin9creative** [comment] 2014-02-07 18:17
Just a FYI - I'm trying to be helpful here.  I honestly don't appreciate the various comments about "would appreciate if you could provide some real answers to the code" or "why are you being secretive? is this a proprietary software?" etc...

**Comment by axilaris** [comment] 2014-02-08 12:30
ok anyway, thanks for being helpful. im just trying to look for some directions in the code itself since some of us would like to extend a bit the functionality.

**Comment by axilaris** [comment] 2014-02-08 13:11
so it seems what you are saying its true. its not suitable for multiuser handling separate publications. are you planning to support this in version 2.0 ?

**Comment by nin9creative** [comment] 2014-02-08 15:43
It supports multiple publications.

It does not support multiple users with their own distinct publications.  The intention of this backend is solely to manage Baker publications for a single publisher or developer which may have multiple people involved in the administration of those publications.

No plans for that.

If you are trying to build some sort of SaaS platform to charge users for access for some publishing solution you are building, then you would be best to build a system from scratch as this was never intended for such a use.

---

**Comment by axilaris** [comment] 2014-02-08 16:44
ok.
i'll probably just try to add a new user_id field into publication and issue table. And get the crud to conditionally query those tables based on the user_id. possibly quite a bit to be done, currently investigating on that.

**Comment by nin9creative** [comment] 2014-02-08 17:15
Ok.

**Comment by nin9creative** [comment] 2014-03-01 15:55
Closing as it seems you must have gotten past this issue...  If not, please reopen.

**Closed as completed by nin9creative** 2014-03-01 15:55 UTC
